config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  resources :posts, only: %i[new create show edit update index]
  resources :channels do
    member do
      post :invite
      post :confirm_invite
    end
  end
  resource :users, only: %i[edit update] do
    collection do
      patch :change_password
    end
  end
  resources :notifications, only: [:update, :index] do
    collection do
      get :mark_as_read_all
    end
  end
  resources :comments, only: %i[create update destroy]


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :admin do
    root to: "home#index"
    resources :categories
  end

  resources :tags, only: %i(show)

  # match '*path', :to => 'application#redirect_to_root_path', via: [:get, :post]

  mount ActionCable.server => '/cable'
end

app/models/channel.rb
class Channel < ApplicationRecord
  mount_uploader :avatar, ChannelAvatarUploader
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'

  has_many :posts, dependent: :destroy
  has_many :users_channels
  has_many :members, through: :users_channels, source: :user
  has_many :comments, as: :resource

  validates :name, presence: true, length: { maximum: Settings.channel.length_name.max}
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :check_current_user
  before_action :set_channel, only: %i[show edit update destroy invite confirm_invite]
  before_action :set_users_channel, only: %i[show confirm_invite]
  before_action :check_owner, only: :update

  def index
    @channels = current_user.channels
    channel_ids = current_user.users_channels.accepted.pluck(:channel_id)
    @sub_channels = Channel.where(id: channel_ids)
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = current_user.channels.new(channel_params)

    if @channel.save
      redirect_to(channels_path)
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def show; end

  def edit; end

  def update
    @channel.update channel_params

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @channel.destroy
    redirect_to channels_path
  end

  def confirm_invite
    @users_channel.send("#{params[:confirm]}!") if @users_channel && @users_channel.waiting?
 
    redirect_to @channel
  end


  def invite
    @user = User.find_by(email: params[:email])

    check_invite_channel if @user.present? && @user.id != current_user.id

    respond_to do |format|
      format.js
    end
  end

  private

  def channel_params
    params.require(:channel).permit(:name, :avatar, :detail)
  end

  def set_channel
    @channel = Channel.find_by(id: params[:id])
  end

  def check_owner
    redirect_to root_path unless @channel.user_id == current_user.id
  end

  def set_users_channel
    @users_channel = current_user.users_channels.find_by(channel_id: params[:id])
  end

  def check_invite_channel
    users_channel = UsersChannel.find_by(user_id: @user.id, channel_id: params[:id])

    if users_channel
      return error = true if users_channel.waiting?
      users_channel.waiting! if users_channel.rejected?
    else
      users_channel = UsersChannel.create(user_id: @user.id, channel_id: params[:id])
    end

    if users_channel.waiting? && !error
      NotificationService.new(to_user: @user, channel: @channel,
        from_user: current_user, key: "invite_channel").perform
    end
  end
end

app/views/channels/_form.html.erb
<%= form_for(@channel, url: channels_path, method: :post, remote: true) do |form| %>
  <div id="error_messages_new_channel" class="alert alert-danger">
    <%= render "shared/error_messages", resource: @channel %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :detail %>
    <%= form.text_area :detail, class: "form-control" %>
  </div>
  <div class="form-group"> 
    <%= form.label :avatar %>
    <%= form.file_field :avatar, id: "inputImageChannel", class: "form-control" %>

    <div class="image-post">
      <img id="imageChannel">
    </div>
  </div>  
  </br >
  <div class="button-create">
      <%= form.submit t(".create_channel"), class: "btn btn-outline-primary" %>
  </div>
<% end %>

<script type="text/javascript">
  $('#inputImageChannel').change(function(){
    const file = this.files[0];
    if (file){
      let reader = new FileReader();
      reader.onload = function(event){
        console.log(event.target.result);
        $('#imageChannel').attr('src', event.target.result);
      }
      reader.readAsDataURL(file);
    }
  });
</script>

app/views/channels/_form_invite.html.erb
<%= form_tag(invite_channel_path, remote: true) do %>
  <div id="error_messages_invite" class="alert-danger-invite">
  </div>
  <div id="success-message-invite" class="alert-success-custom"></div>
    <div class="form-group">
      <label>Mời thành viên</label>
      <div class="search-user">
        <%= email_field_tag :email, "", class: "form-control", placeholder: "Nhập email để mời"%></br> &emsp;
        <div class="submit-invite">
          <%= submit_tag 'Mời', class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/channels/_form_manage.html.erb
<%= form_for(@channel, url: channel_path, method: :patch, remote: true) do |form| %>
  <div id="error_messages_channel" class="alert alert-danger">
    <%= render "shared/error_messages", resource: @channel %>
  </div>

  <div id="success-message" class="alert-success-custom"></div>

  <div class="avatar-channel">
    <% if @channel.avatar_url %>
      <img src="<%= @channel.avatar %>" class="avatar-user" >
    <% else %>
      <%= image_tag("avatar_user_default.jpg", class: "avatar-user") %>
    <% end %>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <div class="form-group"> 
          <%= form.file_field :avatar, id:"file-avatar" %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :detail %>
        <%= form.text_area :detail, class: "form-control", rows: 4 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col d-flex justify-content-end">
      <div class="button-create">
        <%= form.submit t(".update"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %></br>

<script type="text/javascript">
  $(document).ready(function() {
    $("input[id='file-avatar']").hide();

    $(".avatar-channel").click(function() {
      $("input[id='file-avatar']").click();
    });

    $('#file-avatar').change(function(){
      const file = this.files[0];
      if (file){
        let reader = new FileReader();
        reader.onload = function(event){
          $('.avatar-user').attr('src', event.target.result);
        }
        reader.readAsDataURL(file);
      }
    });
  });
</script>

app/views/channels/_home.html.erb
<div id="post" class="tabcontent">
  <div class="card gedf-card">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-between align-items-center">
          <div class="item-avatar">
            <img src="http://i1.taimienphi.vn/tmp/cf/aut/hinh-anh-nguoi-mau.jpg" alt="">
          </div>
          <div class="ml-25">
            <div class="h7 text-muted">Sang vlog</div>
          </div>
        </div>
        <div>
          <div class="dropdown">
            <a href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-ellipsis-h"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><a class="dropdown-item" href="#">Báo Cáo</a></li>
              <li><a class="dropdown-item" href="#">Lưu</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="text-muted h7 mb-2"> <i class="far fa-clock"></i>10 phút trước</div>
      <a class="card-link" href="#">
        <h5 class="card-title">Sang vlog 14 ngày bắt cá và tồn tại trong rừng.</h5>
      </a>

      <p class="card-text">
        Với mọi người hạnh phúc là gì vậy?
        Theo sang khi sang vào rừng 14 ngày cùng nhóc quỳnh sang mới cảm nhận được hạnh phúc nó đơn giản lắm. 
        Là hoàng thành tốt chuyến đi để gửi đến tất cả mọi người
      </p>
    </div>
    <div class="card-footer">
      <p class="card-link"><i class="far fa-thumbs-up"></i> 1.2k Like</p>
    </div>
  </div></br>

  <div class="card gedf-card">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-between align-items-center">
          <div class="item-avatar">
            <img src="http://i1.taimienphi.vn/tmp/cf/aut/hinh-anh-nguoi-mau.jpg" alt="">
          </div>
          <div class="ml-2">
            <div class="h7 text-muted">Sang vlog</div>
          </div>
        </div>
        <div>
          <div class="dropdown">
            <a href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-ellipsis-h"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><a class="dropdown-item" href="#">Báo Cáo</a></li>
              <li><a class="dropdown-item" href="#">Lưu</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="text-muted h7 mb-2"> <i class="far fa-clock"></i>10 phút trước</div>
      <a class="card-link" href="#">
        <h5 class="card-title">Sang vlog 14 ngày bắt cá và tồn tại trong rừng.</h5>
      </a>

      <p class="card-text">
        Với mọi người hạnh phúc là gì vậy?
        Theo sang khi sang vào rừng 14 ngày cùng nhóc quỳnh sang mới cảm nhận được hạnh phúc nó đơn giản lắm. 
        Là hoàng thành tốt chuyến đi để gửi đến tất cả mọi người
      </p>
    </div>
    <div class="card-footer">
      <p class="card-link"><i class="far fa-thumbs-up"></i> 1.2k Like</p>
    </div>
  </div></br>

  <div class="card gedf-card">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-between align-items-center">
          <div class="item-avatar">
            <img src="http://i1.taimienphi.vn/tmp/cf/aut/hinh-anh-nguoi-mau.jpg" alt="">
          </div>
          <div class="ml-2">
            <div class="h7 text-muted">Sang vlog</div>
          </div>
        </div>
        <div>
          <div class="dropdown">
            <a href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-ellipsis-h"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><a class="dropdown-item" href="#">Báo Cáo</a></li>
              <li><a class="dropdown-item" href="#">Lưu</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="text-muted h7 mb-2"> <i class="far fa-clock"></i>10 phút trước</div>
      <a class="card-link" href="#">
        <h5 class="card-title">Sang vlog 14 ngày bắt cá và tồn tại trong rừng.</h5>
      </a>

      <p class="card-text">
        Với mọi người hạnh phúc là gì vậy?
        Theo sang khi sang vào rừng 14 ngày cùng nhóc quỳnh sang mới cảm nhận được hạnh phúc nó đơn giản lắm. 
        Là hoàng thành tốt chuyến đi để gửi đến tất cả mọi người
      </p>
      <div class="card-image">
        <img src="http://i1.taimienphi.vn/tmp/cf/aut/hinh-anh-nguoi-mau.jpg" alt="">
      </div>
    </div>
    <div class="card-footer">
      <p class="card-link"><i class="far fa-thumbs-up"></i> 1.2k Like</p>
    </div>
  </div>
</div>

app/views/channels/_introduce.html.erb
<div id="introduce" class="tabcontent">
  <p><%= @channel.detail %></p>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $("#introduce").show();
  });
</script>

app/views/channels/_manage.html.erb
<div id="manage" class="tabcontent">
  <%= render "channels/form_manage" %>

  <div id="form-invite" class="mt-40">
    <%= render "channels/form_invite" %>
  </div>
</div>

app/views/channels/create.js.erb
$("#new-channel").html("<%= j render('channels/form') %>");
$("#error_messages_new_channel").html("<%= j render('shared/error_messages', resource: @channel) %>");

app/views/channels/index.html.erb
<div class="container mt-15">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <div class="box-channel">
        <h4>Các channel của bạn</h4>
        <% if @channels.present? %>
          <ul>
            <% @channels.each do |channel| %>
              <%= link_to channel do %>
                <li>
                  <div class="avatar-main-channel">
                    <% if channel.avatar_url %>
                      <img src="<%= channel.avatar %>" >
                    <% else %>
                      <%= image_tag("avatar_user_default.jpg") %>
                    <% end %>
                  </div> 
                  &nbsp; <p class="my-channel"><%= channel.name %></p>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% else %>
          <p> Bạn chưa tạo channel nào </p>
        <% end %>

        <%= link_to "<button class= 'btn btn-primary'>Tạo kênh</button>".html_safe, new_channel_path %>
      </div>
    </div>
    
    <div class="col-sm-12 col-md-6">
      <div class="box-channel">
        <h4>Các channel bạn tham gia</h4>
        <% if @sub_channels.present? %>
          <ul>
            <% @sub_channels.each do |channel| %>
              <%= link_to channel do %>
                <li>
                  <div class="avatar-main-channel">
                    <% if channel.avatar_url %>
                      <img src="<%= channel.avatar %>" >
                    <% else %>
                      <%= image_tag("avatar_user_default.jpg") %>
                    <% end %>
                  </div> 
                  &nbsp; <p class="my-channel"><%= channel.name %></p>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% else %>
          <p> Bạn chưa tham gia channel nào </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/channels/invite.js.erb
<% if @user.blank? %>
  $("#error_messages_invite").html("<p class='alert alert-danger'>Người dùng không tồn tại</p>");
  $("#success-message-invite").html("");
<% elsif @user.id == current_user.id %>
  $("#error_messages_invite").html("<p class='alert alert-danger'>Bạn không thể mời chính mình</p>");
  $("#success-message-invite").html("");
<% else %>
  $("#success-message-invite").html("<p class='alert alert-success'>Mời thành công</p>");
  $("#error_messages_invite").html("");
<% end %>

app/views/channels/new.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="container" id="new-channel">
      <%= render "channels/form" %>
    </div>
  </div>
</div>

app/views/channels/show.html.erb
<div class="container">
  <% if @users_channel.present? && @users_channel.waiting? %>
    <div class="confirm-invite-channel">
      <p class="alert alert-success">
        Bạn nhận được lời mời tham gia channel này.
        <%= link_to "Chấp nhận", confirm_invite_channel_path(confirm: "accepted"), method: :post %> 
        hoặc 
        <%= link_to 'Từ chối', confirm_invite_channel_path(confirm: "rejected"), method: :post %>
      </p>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-12 col-md-4 col-lg-3">
      <div class="channel-sidebar">
        <div class="avatar-main">
          <% if @channel.avatar_url %>
            <img src="<%= @channel.avatar %>" >
          <% else %>
            <%= image_tag("avatar_user_default.jpg") %>
          <% end %>
        </div>
        <div class="channel-name">
          <h4><b><%= @channel.name %></b></h4>
          <p> 1,233 Followers </p>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-8 col-lg-9 detail">
      <div class="bd-solid">
        <div class="tab">
          <button class="tablinks tabchannel" onclick="OpenProfile(event, 'introduce')">Giới thiệu</button>
          <button class="tablinks tabchannel" onclick="OpenProfile(event, 'post')">Post</button>
          <% if @channel.user_id == current_user.id %>
            <button class="tablinks tabchannel" onclick="OpenProfile(event, 'manage')">Quản lý</button>
          <% end %>
        </div>
        <%= render "channels/introduce" %>

        <%= render "channels/home" %>

        <%= render "channels/manage" %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function OpenProfile(evt, profile) {
    var i, tabcontent, tablinks;

    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }

    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    document.getElementById(profile).style.display = "block";
    evt.currentTarget.className += " active";
  }
</script>

app/views/channels/update.js.erb
$("#manage").html("<%= j render('channels/form_manage') %>");
$("#error_messages_channel").html("<%= j render('shared/error_messages', resource: @channel) %>");
<% if @channel.errors.blank? %>
  $("#success-message").html("<p>Cập nhật thành công</p>");
<% end %>