config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  resources :posts, only: %i[new create show edit update index]
  resources :channels do
    member do
      post :invite
      post :confirm_invite
    end
  end
  resource :users, only: %i[edit update] do
    collection do
      patch :change_password
    end
  end
  resources :notifications, only: [:update, :index] do
    collection do
      get :mark_as_read_all
    end
  end
  resources :comments, only: %i[create update destroy]


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :admin do
    root to: "home#index"
    resources :categories
  end

  resources :tags, only: %i(show)

  # match '*path', :to => 'application#redirect_to_root_path', via: [:get, :post]

  mount ActionCable.server => '/cable'
end

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <a href="index3.html" class="brand-link">
    <%= image_tag('uytinvl.png', class: "brand-image img-circle elevation-3") %>
    <span class="brand-text font-weight-light">Uytinvl</span>
  </a>

  <div class="sidebar">
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to "<i class='nav-icon fas fa-tachometer-alt'></i><p>Dash board</p>".html_safe,  admin_root_path, class: ["nav-link", is_controller?('admin/home')].compact.join(" ") %>
        </li>
        <li class="nav-item">
          <%= link_to "<i class='nav-icon fas fa-th'></i><p>Category</p>".html_safe, admin_categories_path, class: ["nav-link", is_controller?('admin/categories')].compact.join(" ") %>
        </li>
        <li class="nav-item">
          <%= link_to "<i class='fas fa-sign-out-alt'></i> Logout".html_safe, destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to "<i class='fas fa-home'></i> Back to home".html_safe, root_path, class: "nav-link" %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/admin/sidebar" %>
    <%= yield %>
  </body> 
</html>