config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  resources :posts, only: %i[new create show edit update index]
  resources :channels do
    member do
      post :invite
      post :confirm_invite
    end
  end
  resource :users, only: %i[edit update] do
    collection do
      patch :change_password
    end
  end
  resources :notifications, only: [:update, :index] do
    collection do
      get :mark_as_read_all
    end
  end
  resources :comments, only: %i[create update destroy]


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :admin do
    root to: "home#index"
    resources :categories
  end

  resources :tags, only: %i(show)

  # match '*path', :to => 'application#redirect_to_root_path', via: [:get, :post]

  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostImageUploader
  has_rich_text :content

  belongs_to :user
  belongs_to :category
  belongs_to :channel, optional: true

  has_many :tags_posts
  has_many :tags, through: :tags_posts
  has_many :comments, as: :resource

  validates :title, presence: true
  validates :image, presence: true
  validate :rich_text_content_presence
  validate :channel_must_belongs_to_user, if: -> { channel_id.present? }

  scope :newest, -> { order(created_at: :desc) }

  def rich_text_content_presence
    return if rich_text_content.body.to_s.length > Settings.rich_text_content.length_default

    errors.add(:rich_text_content, :blank)
  end

  def channel_must_belongs_to_user
    return if (user.channels.pluck(:id) + user.sub_channels.where(users_channels: { status: :accepted })
      .pluck(:id)).include?(channel_id)

    errors.add(:channel_id, :invalid)
  end

  def tag_post
    tags.pluck(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_current_user, except: %i(index show)
  before_action :set_post, only: %i(show edit update)
  before_action :check_owner, only: %i(edit update)

  def index
    redirect_to root_path
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    ActiveRecord::Base.transaction do
      if @post.save
        tags = JSON.parse(params[:post][:tags]).map{|tag| reformat(tag.dig("value"))}
        tags.map do |tag_name|
          tag = Tag.find_or_create_by(name: tag_name)
          TagsPost.find_or_create_by(tag_id: tag.id, post_id: @post.id)
        end

        redirect_to @post
      else
        render :new
      end
    end
  end

  def show
    @comments = @post.comments.includes(:user, parent_comment: :user).get_parents
  end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      if @post.update post_update_params
        tags = JSON.parse(params[:post][:tags]).map{|tag| reformat(tag.dig("value"))}

        @post.tags_posts.includes(:tag).map do |tags_post|
          next if tags.include?(tags_post.tag.name)

          tags_post.destroy!
        end

        tags.map do |tag_name|
          tag = Tag.find_or_create_by(name: tag_name)
          TagsPost.find_or_create_by(tag_id: tag.id, post_id: @post.id)
        end
        redirect_to @post
      else
        render :edit
      end
    end
  end

  private

  def set_post
    @post = Post.find_by(id: params[:id])
    redirect_to root_path unless @post
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :image, :channel_id, :tag)
  end

  def post_update_params
    params.require(:post).permit(:title, :content, :category_id, :image, :tag)
  end

  def check_owner
    redirect_to root_path unless @post.user_id == current_user.id
  end
end

app/views/posts/_form.html.erb
<%= form_for(post, url: url, method: method) do |form| %>
  <div id="error_messages_post" class="alert alert-danger">
    <%= render "shared/error_messages", resource: post %>
  </div>

  <div class="row">
    <div class="form-group col-md-12 col-lg-6">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group col-md-12 col-lg-6">
      <%= form.label :author %>
      <%= form.select(
        :channel_id,
        options_for_select(([[current_user.name, nil]] + current_user.generate_options_channel), post.channel_id),
        {},
        class: "form-control",
        disabled: post.persisted?)
      %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.rich_text_area :content , class: "rich_text_area" %>
  </div>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.select(:category_id, options_for_select(Category.generate_options, post.category_id), {}, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= form.label :tags %>
    <%= form.text_field :tags, value: @post.tag_post.join(", "), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: "inputImagePost", class: "form-control" %>

    <div class="image-post">
      <img id="imagePost" src="<%= post.image_url %>">
    </div>
  </div>

  <div class="button-create">
    <% if post.persisted? %>
      <%= form.submit t(".edit_post"), class: "btn btn-outline-primary" %>
    <% else %>
      <%= form.submit t(".create_post"), class: "btn btn-outline-primary" %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
$('#inputImagePost').change(function(){
  const file = this.files[0];
  if (file){
    let reader = new FileReader();
    reader.onload = function(event){
      console.log(event.target.result);
      $('#imagePost').attr('src', event.target.result);
    }
    reader.readAsDataURL(file);
  }
});
</script>

app/views/posts/_post.html.erb
<div class="col-6 col-lg-3">
  <div class="post-box">
    <%= link_to post do %>
      <img src="<%= post.image %>" />
      <div class="post-box-title">
        <p><%= post.title %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <%= render "form", post: @post, url: post_path, method: :patch %>
</div>

app/views/posts/index.html.erb
<div class="container posts">
  <h4> Các bài viết liên quan </h4>
  <div class="suggesting">
    <div class="row" id="posts">
      <% @posts.map do |post| %>
        <div class="col-12 col-sm-12 col-md-6 col-lg-3">
          <div class="post-box">
            <%= link_to post do %>
              <img src="<%= post.image %>" />
              <div class="post-box-title">
                <p><%= post.title %></p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= render "form", post: @post, url: posts_path, method: :post %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="body-post">
    <div class="post-header">
      <div class="category"><p><i><%= @post.created_at.in_time_zone(7).strftime(Settings.date.format) %></i></p></div>

      <div class="dropdown">
        <a href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-ellipsis-h color-bl"></i>
        </a>
        <ul class="dropdown-menu custom-inset" aria-labelledby="dropdownMenuLink">
          <% if current_user && current_user.id == @post.user_id %>
            <li>
              <%= link_to "Chỉnh sửa", edit_post_path(@post), class: 'dropdown-item' %>
            </li>
          <% else %>
            <li><a class="dropdown-item">Báo cáo</a></li>
          <% end %>
          <li><a class="dropdown-item">Chia sẻ</a></li>
        </ul>
      </div>
    </div>

    <h1>
      <%= @post.title %>
    </h1>

    <div class="author-post">
      <div class="left">
        <!-- handle user_path -->
        <%= link_to "<div class='avatar-post'>
          #{@post.channel_id ? avatar_of(@post.channel) : avatar_of(@post.user)}
          </div>".html_safe,
          @post.channel_id ? @post.channel : root_path
        %>
      </div>

      <div class="mid">
        <p><%= @post.channel_id ? @post.channel.name : @post.user.name %> | 1.k followers</p>
        <button class="btn btn-success" title="huỷ theo dõi"><i class="fas fa-check"></i> Đang theo dõi</button>
      </div>
    </div>

    <div class="clear-both">
    </div>

    <div class="content-post">
      <%= @post.content %>
    </div>
    <% if @post.tags.present?%>
      <div class="tags mt-20">
        <i class="fas fa-tags"></i>
          <% @post.tags.map do |tag| %>
            <%= link_to tag_path(tag) do %>
              <span class="tag-item"><%= tag.name %></span>
            <% end %>
          <% end %>
      </div>
    <% end %>

    <div class="comment-post">
      <h5>Bình luận</h5>

      <% if current_user %>
        <div class="form-comment-post">
          <div class="form-group">
            <div class="comment-author">
              <div class="wrapper-img-post">
                <%= avatar_of current_user %>
              </div>
              <p class="author-name"><%= current_user.name %></p>
            </div>

            <div class="input-comment">
              <%= render "comments/form_comment", post: @post %>
            </div>
          </div>
        </div>
      <% end %>

      <hr />

      <div class="content-comment-post">
        <%= render @comments %>
      </div>
    </div>
  </div>
</div>